name = "cloudflare-temp-email"
main = "worker/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_PASSWORDS = "mypass123"
DOMAINS = "freeopenclawskills.cn"
DISABLE_TURNSTILE = "true"

[[d1_databases]]
binding = "DB"
database_name = "temp_email_db"
database_id = ""
